finchcollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # '' represents the "starts with" path
    path('', include('main_app.urls')),
]

main_app/urls.py

from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path("about/", views.about, name='about'),
  path("n64_index/", views.n64_index, name = 'n64_index'),
  path('n64_index/<int:game_id>/', views.games_detail, name='detail'),
  path('n64_index/create/', views.GameCreate.as_view(), name="game-create"),
  path('n64_index/<int:pk>/update/', views.GameUpdate.as_view(), name='game-update'),
  path('n64_index/<int:pk>/delete/', views.GameDelete.as_view(),  name='game-delete'),
  path('n64_index/<int:game_id>/add_levels/' , views.add_levels, name='add_levels'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Game(models.Model):
    name = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    #notion for (B)reakfast (L)unch (D)inner to be used here
    franchise = models.CharField(max_length=100)
    #notion for (B)reakfast (L)unch (D)inner to be used here
    description =  models.TextField(max_length=250)
    

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('detail', kwargs={'game_id': self.id})
    
class levels(models.Model):
    number = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)    

    def __str__(self):
        return self.name


# class Console(models.Model):
#     name = models.CharField(max_length=100)
#     manufacturer = models.CharField(max_length=100)
#     Generation = models.CharField(max_length=100)
#     description =  models.TextField(max_length=250)

main_app/forms.py
from django.forms import ModelForm
from .models import levels

class LevelsForm(ModelForm):
  class Meta:
    model = levels
    fields = ['number', 'name']

main_app/templates/main_app/forms.py
from django.forms import ModelForm
from .models import levels

class LevelsForm(ModelForm):
  class Meta:
    model = levels
    fields = ['number', 'name']

main_app/views.py
from django.shortcuts import render, redirect
import os
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Game
from .forms import LevelsForm

# Define the home view


def home(request):
    # Include an .html file extension - unlike when rendering EJS templates
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def n64_index(request):
    n64 = Game.objects.all()
    return render(request, 'N64_games/index.html', {'n64': n64})


def games_detail(request, game_id):
    game = Game.objects.get(id=game_id)
    print(game_id)
    levels_form = LevelsForm()
    return render(request, 'N64_games/details.html', {'n64': game, "levels_form": levels_form})


def add_levels(request, game_id):
    form = LevelsForm(request.POST)
    if form.is_valid():
        new_level = form.save(commit=False)
        new_level.game_id = game_id
        new_level.save()
    return redirect("detail", game_id=game_id)

def some_function(request):
    secret_key = os.environ['SECRET_KEY']


class GameCreate(CreateView):
    model = Game
    fields = '__all__'


class GameUpdate(UpdateView):
    model = Game
    fields = ["genre", "franchise", "description"]


class GameDelete(DeleteView):
    model = Game
    success_url = "/n64_index"

main_app/templates/N64_games/details.html
{% extends 'base.html' %}
{% block content %}

<h1>Game Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ n64.name }}</span>
    <p>Genre: {{ n64.genre }}</p>
    <p>franchise: {{ n64.franchise }}</p>
    <p> Description: {{ n64.description }}</p>
  </div>
  <div class = "card-action">
    <a href ="{% url 'game-update' n64.id %}">Edit</a>
    <a href ="{% url 'game-delete' n64.id %}">Delete</a>
  </div>
</div>
<div class="col s6">
  <form action ="{% url 'add_levels' n64.id %}"method ="POST">
    {% csrf_token %}
    {{levels_form.as_p}}
    <input type ="submit" class="btn" value="Add Levels">
  </form>
  <table class="striped">
    <thead>
      <tr><th>Level Number:</th><th>Level Name:</th></tr>
    </thead>
    <tbody>
      {% for levels in n64.levels_set.all %}
        <tr>
          <td>{{levels.number}}</td>
          <td>{{levels.name}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{% endblock %}

main_app/templates/N64_games/index.html
{% extends 'base.html' %}
{% block content %}

<h1>N64 Game List</h1>

<h2>All my games</h2>

{% for n64 in n64 %}
  <div class="card">
    <a href="/n64_index/{{n64.id}}">
    <div class="card-content">
      <span class="card-title">{{ n64.name }}</span>
      <p>franchise: {{ n64.franchise }}</p>
    </div>
  </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the N64 Collector</h1>
<hr>
<p>Hello, I'm Ciaran and this is my page.
    I collect N64 games. Over my life i've had many games, consoles, accesories etc however i've always ended up selling them.
    Now, i'm going to be officially collecting them and this is where you can find out what I have.</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>N64 Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo"> &nbsp;&nbsp;N64 Collector</a></li>

        </ul>
        <ul class="right">
          
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href= "{% url 'game-create' %}">Add a game</a></li>
          <li><a href="{% url 'n64_index' %}" >&nbsp;&nbsp; all N64 games</a></li>
          </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 N64 Collection &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Home page</h1>
    <img src="https://i.kym-cdn.com/photos/images/original/000/487/850/d22.gif" alt="spinning logo">
    {% endblock %}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Game</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' game.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Game</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}